// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incident.proto

package io.vigilante;

public final class IncidentProtos {
  private IncidentProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IncidentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vigilante.Incident)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string description = 2;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 2;</code>
     */
    String getDescription();
    /**
     * <code>optional string description = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional int64 start = 3;</code>
     */
    boolean hasStart();
    /**
     * <code>optional int64 start = 3;</code>
     */
    long getStart();

    /**
     * <code>optional string key = 4;</code>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 4;</code>
     */
    String getKey();
    /**
     * <code>optional string key = 4;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional .vigilante.Service service = 5;</code>
     */
    boolean hasService();
    /**
     * <code>optional .vigilante.Service service = 5;</code>
     */
    ServiceProtos.Service getService();
    /**
     * <code>optional .vigilante.Service service = 5;</code>
     */
    ServiceProtos.ServiceOrBuilder getServiceOrBuilder();

    /**
     * <code>optional .vigilante.Team team = 6;</code>
     */
    boolean hasTeam();
    /**
     * <code>optional .vigilante.Team team = 6;</code>
     */
    TeamProtos.Team getTeam();
    /**
     * <code>optional .vigilante.Team team = 6;</code>
     */
    TeamProtos.TeamOrBuilder getTeamOrBuilder();

    /**
     * <code>optional .vigilante.Incident.StateType state = 7;</code>
     */
    boolean hasState();
    /**
     * <code>optional .vigilante.Incident.StateType state = 7;</code>
     */
    Incident.StateType getState();
  }
  /**
   * Protobuf type {@code vigilante.Incident}
   */
  public static final class Incident extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vigilante.Incident)
      IncidentOrBuilder {
    // Use Incident.newBuilder() to construct.
    private Incident(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Incident(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Incident defaultInstance;
    public static Incident getDefaultInstance() {
      return defaultInstance;
    }

    public Incident getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Incident(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              description_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              start_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              key_ = bs;
              break;
            }
            case 42: {
              ServiceProtos.Service.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = service_.toBuilder();
              }
              service_ = input.readMessage(ServiceProtos.Service.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(service_);
                service_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              TeamProtos.Team.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = team_.toBuilder();
              }
              team_ = input.readMessage(TeamProtos.Team.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(team_);
                team_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              StateType value = StateType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                state_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IncidentProtos.internal_static_vigilante_Incident_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IncidentProtos.internal_static_vigilante_Incident_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Incident.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Incident> PARSER =
        new com.google.protobuf.AbstractParser<Incident>() {
      public Incident parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Incident(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Incident> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code vigilante.Incident.StateType}
     */
    public enum StateType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RESOLVED = 0;</code>
       */
      RESOLVED(0, 0),
      /**
       * <code>TRIGGERED = 1;</code>
       */
      TRIGGERED(1, 1),
      /**
       * <code>ACKNOWLEDGED = 2;</code>
       */
      ACKNOWLEDGED(2, 2),
      ;

      /**
       * <code>RESOLVED = 0;</code>
       */
      public static final int RESOLVED_VALUE = 0;
      /**
       * <code>TRIGGERED = 1;</code>
       */
      public static final int TRIGGERED_VALUE = 1;
      /**
       * <code>ACKNOWLEDGED = 2;</code>
       */
      public static final int ACKNOWLEDGED_VALUE = 2;


      public final int getNumber() { return value; }

      public static StateType valueOf(int value) {
        switch (value) {
          case 0: return RESOLVED;
          case 1: return TRIGGERED;
          case 2: return ACKNOWLEDGED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StateType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<StateType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StateType>() {
              public StateType findValueByNumber(int number) {
                return StateType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Incident.getDescriptor().getEnumTypes().get(0);
      }

      private static final StateType[] VALUES = values();

      public static StateType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private StateType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:vigilante.Incident.StateType)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private Object description_;
    /**
     * <code>optional string description = 2;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string description = 2;</code>
     */
    public String getDescription() {
      Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_FIELD_NUMBER = 3;
    private long start_;
    /**
     * <code>optional int64 start = 3;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 start = 3;</code>
     */
    public long getStart() {
      return start_;
    }

    public static final int KEY_FIELD_NUMBER = 4;
    private Object key_;
    /**
     * <code>optional string key = 4;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string key = 4;</code>
     */
    public String getKey() {
      Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 4;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_FIELD_NUMBER = 5;
    private ServiceProtos.Service service_;
    /**
     * <code>optional .vigilante.Service service = 5;</code>
     */
    public boolean hasService() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .vigilante.Service service = 5;</code>
     */
    public ServiceProtos.Service getService() {
      return service_;
    }
    /**
     * <code>optional .vigilante.Service service = 5;</code>
     */
    public ServiceProtos.ServiceOrBuilder getServiceOrBuilder() {
      return service_;
    }

    public static final int TEAM_FIELD_NUMBER = 6;
    private TeamProtos.Team team_;
    /**
     * <code>optional .vigilante.Team team = 6;</code>
     */
    public boolean hasTeam() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .vigilante.Team team = 6;</code>
     */
    public TeamProtos.Team getTeam() {
      return team_;
    }
    /**
     * <code>optional .vigilante.Team team = 6;</code>
     */
    public TeamProtos.TeamOrBuilder getTeamOrBuilder() {
      return team_;
    }

    public static final int STATE_FIELD_NUMBER = 7;
    private StateType state_;
    /**
     * <code>optional .vigilante.Incident.StateType state = 7;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .vigilante.Incident.StateType state = 7;</code>
     */
    public StateType getState() {
      return state_;
    }

    private void initFields() {
      id_ = "";
      description_ = "";
      start_ = 0L;
      key_ = "";
      service_ = ServiceProtos.Service.getDefaultInstance();
      team_ = TeamProtos.Team.getDefaultInstance();
      state_ = StateType.RESOLVED;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasService()) {
        if (!getService().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTeam()) {
        if (!getTeam().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, start_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getKeyBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, service_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, team_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, state_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, start_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getKeyBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, service_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, team_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, state_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Incident parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Incident parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Incident parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Incident parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Incident parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Incident parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Incident parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Incident parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Incident parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Incident parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Incident prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vigilante.Incident}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vigilante.Incident)
        IncidentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IncidentProtos.internal_static_vigilante_Incident_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IncidentProtos.internal_static_vigilante_Incident_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Incident.class, Builder.class);
      }

      // Construct using io.vigilante.IncidentProtos.Incident.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getServiceFieldBuilder();
          getTeamFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        start_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (serviceBuilder_ == null) {
          service_ = ServiceProtos.Service.getDefaultInstance();
        } else {
          serviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (teamBuilder_ == null) {
          team_ = TeamProtos.Team.getDefaultInstance();
        } else {
          teamBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        state_ = StateType.RESOLVED;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IncidentProtos.internal_static_vigilante_Incident_descriptor;
      }

      public Incident getDefaultInstanceForType() {
        return Incident.getDefaultInstance();
      }

      public Incident build() {
        Incident result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Incident buildPartial() {
        Incident result = new Incident(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.start_ = start_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (serviceBuilder_ == null) {
          result.service_ = service_;
        } else {
          result.service_ = serviceBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (teamBuilder_ == null) {
          result.team_ = team_;
        } else {
          result.team_ = teamBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Incident) {
          return mergeFrom((Incident)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Incident other) {
        if (other == Incident.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000002;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasStart()) {
          setStart(other.getStart());
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000008;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasService()) {
          mergeService(other.getService());
        }
        if (other.hasTeam()) {
          mergeTeam(other.getTeam());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasService()) {
          if (!getService().isInitialized()) {
            
            return false;
          }
        }
        if (hasTeam()) {
          if (!getTeam().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Incident parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Incident) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private Object description_ = "";
      /**
       * <code>optional string description = 2;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public String getDescription() {
        Object ref = description_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public Builder setDescription(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
        return this;
      }

      private long start_ ;
      /**
       * <code>optional int64 start = 3;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 start = 3;</code>
       */
      public long getStart() {
        return start_;
      }
      /**
       * <code>optional int64 start = 3;</code>
       */
      public Builder setStart(long value) {
        bitField0_ |= 0x00000004;
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 start = 3;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000004);
        start_ = 0L;
        onChanged();
        return this;
      }

      private Object key_ = "";
      /**
       * <code>optional string key = 4;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string key = 4;</code>
       */
      public String getKey() {
        Object ref = key_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string key = 4;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 4;</code>
       */
      public Builder setKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 4;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 4;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        key_ = value;
        onChanged();
        return this;
      }

      private ServiceProtos.Service service_ = ServiceProtos.Service.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ServiceProtos.Service, ServiceProtos.Service.Builder, ServiceProtos.ServiceOrBuilder> serviceBuilder_;
      /**
       * <code>optional .vigilante.Service service = 5;</code>
       */
      public boolean hasService() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .vigilante.Service service = 5;</code>
       */
      public ServiceProtos.Service getService() {
        if (serviceBuilder_ == null) {
          return service_;
        } else {
          return serviceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .vigilante.Service service = 5;</code>
       */
      public Builder setService(ServiceProtos.Service value) {
        if (serviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          service_ = value;
          onChanged();
        } else {
          serviceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .vigilante.Service service = 5;</code>
       */
      public Builder setService(
          ServiceProtos.Service.Builder builderForValue) {
        if (serviceBuilder_ == null) {
          service_ = builderForValue.build();
          onChanged();
        } else {
          serviceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .vigilante.Service service = 5;</code>
       */
      public Builder mergeService(ServiceProtos.Service value) {
        if (serviceBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              service_ != ServiceProtos.Service.getDefaultInstance()) {
            service_ =
              ServiceProtos.Service.newBuilder(service_).mergeFrom(value).buildPartial();
          } else {
            service_ = value;
          }
          onChanged();
        } else {
          serviceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .vigilante.Service service = 5;</code>
       */
      public Builder clearService() {
        if (serviceBuilder_ == null) {
          service_ = ServiceProtos.Service.getDefaultInstance();
          onChanged();
        } else {
          serviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .vigilante.Service service = 5;</code>
       */
      public ServiceProtos.Service.Builder getServiceBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getServiceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .vigilante.Service service = 5;</code>
       */
      public ServiceProtos.ServiceOrBuilder getServiceOrBuilder() {
        if (serviceBuilder_ != null) {
          return serviceBuilder_.getMessageOrBuilder();
        } else {
          return service_;
        }
      }
      /**
       * <code>optional .vigilante.Service service = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ServiceProtos.Service, ServiceProtos.Service.Builder, ServiceProtos.ServiceOrBuilder>
          getServiceFieldBuilder() {
        if (serviceBuilder_ == null) {
          serviceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ServiceProtos.Service, ServiceProtos.Service.Builder, ServiceProtos.ServiceOrBuilder>(
                  getService(),
                  getParentForChildren(),
                  isClean());
          service_ = null;
        }
        return serviceBuilder_;
      }

      private TeamProtos.Team team_ = TeamProtos.Team.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          TeamProtos.Team, TeamProtos.Team.Builder, TeamProtos.TeamOrBuilder> teamBuilder_;
      /**
       * <code>optional .vigilante.Team team = 6;</code>
       */
      public boolean hasTeam() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .vigilante.Team team = 6;</code>
       */
      public TeamProtos.Team getTeam() {
        if (teamBuilder_ == null) {
          return team_;
        } else {
          return teamBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .vigilante.Team team = 6;</code>
       */
      public Builder setTeam(TeamProtos.Team value) {
        if (teamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          team_ = value;
          onChanged();
        } else {
          teamBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .vigilante.Team team = 6;</code>
       */
      public Builder setTeam(
          TeamProtos.Team.Builder builderForValue) {
        if (teamBuilder_ == null) {
          team_ = builderForValue.build();
          onChanged();
        } else {
          teamBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .vigilante.Team team = 6;</code>
       */
      public Builder mergeTeam(TeamProtos.Team value) {
        if (teamBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              team_ != TeamProtos.Team.getDefaultInstance()) {
            team_ =
              TeamProtos.Team.newBuilder(team_).mergeFrom(value).buildPartial();
          } else {
            team_ = value;
          }
          onChanged();
        } else {
          teamBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .vigilante.Team team = 6;</code>
       */
      public Builder clearTeam() {
        if (teamBuilder_ == null) {
          team_ = TeamProtos.Team.getDefaultInstance();
          onChanged();
        } else {
          teamBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .vigilante.Team team = 6;</code>
       */
      public TeamProtos.Team.Builder getTeamBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getTeamFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .vigilante.Team team = 6;</code>
       */
      public TeamProtos.TeamOrBuilder getTeamOrBuilder() {
        if (teamBuilder_ != null) {
          return teamBuilder_.getMessageOrBuilder();
        } else {
          return team_;
        }
      }
      /**
       * <code>optional .vigilante.Team team = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          TeamProtos.Team, TeamProtos.Team.Builder, TeamProtos.TeamOrBuilder>
          getTeamFieldBuilder() {
        if (teamBuilder_ == null) {
          teamBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              TeamProtos.Team, TeamProtos.Team.Builder, TeamProtos.TeamOrBuilder>(
                  getTeam(),
                  getParentForChildren(),
                  isClean());
          team_ = null;
        }
        return teamBuilder_;
      }

      private StateType state_ = StateType.RESOLVED;
      /**
       * <code>optional .vigilante.Incident.StateType state = 7;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .vigilante.Incident.StateType state = 7;</code>
       */
      public StateType getState() {
        return state_;
      }
      /**
       * <code>optional .vigilante.Incident.StateType state = 7;</code>
       */
      public Builder setState(StateType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .vigilante.Incident.StateType state = 7;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000040);
        state_ = StateType.RESOLVED;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vigilante.Incident)
    }

    static {
      defaultInstance = new Incident(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:vigilante.Incident)
  }

  public interface IncidentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vigilante.Incidents)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .vigilante.Incident incident = 1;</code>
     */
    java.util.List<Incident>
        getIncidentList();
    /**
     * <code>repeated .vigilante.Incident incident = 1;</code>
     */
    Incident getIncident(int index);
    /**
     * <code>repeated .vigilante.Incident incident = 1;</code>
     */
    int getIncidentCount();
    /**
     * <code>repeated .vigilante.Incident incident = 1;</code>
     */
    java.util.List<? extends IncidentOrBuilder>
        getIncidentOrBuilderList();
    /**
     * <code>repeated .vigilante.Incident incident = 1;</code>
     */
    IncidentOrBuilder getIncidentOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code vigilante.Incidents}
   */
  public static final class Incidents extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vigilante.Incidents)
      IncidentsOrBuilder {
    // Use Incidents.newBuilder() to construct.
    private Incidents(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Incidents(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Incidents defaultInstance;
    public static Incidents getDefaultInstance() {
      return defaultInstance;
    }

    public Incidents getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Incidents(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                incident_ = new java.util.ArrayList<Incident>();
                mutable_bitField0_ |= 0x00000001;
              }
              incident_.add(input.readMessage(Incident.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          incident_ = java.util.Collections.unmodifiableList(incident_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IncidentProtos.internal_static_vigilante_Incidents_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IncidentProtos.internal_static_vigilante_Incidents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Incidents.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Incidents> PARSER =
        new com.google.protobuf.AbstractParser<Incidents>() {
      public Incidents parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Incidents(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Incidents> getParserForType() {
      return PARSER;
    }

    public static final int INCIDENT_FIELD_NUMBER = 1;
    private java.util.List<Incident> incident_;
    /**
     * <code>repeated .vigilante.Incident incident = 1;</code>
     */
    public java.util.List<Incident> getIncidentList() {
      return incident_;
    }
    /**
     * <code>repeated .vigilante.Incident incident = 1;</code>
     */
    public java.util.List<? extends IncidentOrBuilder>
        getIncidentOrBuilderList() {
      return incident_;
    }
    /**
     * <code>repeated .vigilante.Incident incident = 1;</code>
     */
    public int getIncidentCount() {
      return incident_.size();
    }
    /**
     * <code>repeated .vigilante.Incident incident = 1;</code>
     */
    public Incident getIncident(int index) {
      return incident_.get(index);
    }
    /**
     * <code>repeated .vigilante.Incident incident = 1;</code>
     */
    public IncidentOrBuilder getIncidentOrBuilder(
        int index) {
      return incident_.get(index);
    }

    private void initFields() {
      incident_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getIncidentCount(); i++) {
        if (!getIncident(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < incident_.size(); i++) {
        output.writeMessage(1, incident_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < incident_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, incident_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Incidents parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Incidents parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Incidents parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Incidents parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Incidents parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Incidents parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Incidents parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Incidents parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Incidents parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Incidents parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Incidents prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vigilante.Incidents}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vigilante.Incidents)
        IncidentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IncidentProtos.internal_static_vigilante_Incidents_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IncidentProtos.internal_static_vigilante_Incidents_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Incidents.class, Builder.class);
      }

      // Construct using io.vigilante.IncidentProtos.Incidents.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIncidentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (incidentBuilder_ == null) {
          incident_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          incidentBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IncidentProtos.internal_static_vigilante_Incidents_descriptor;
      }

      public Incidents getDefaultInstanceForType() {
        return Incidents.getDefaultInstance();
      }

      public Incidents build() {
        Incidents result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Incidents buildPartial() {
        Incidents result = new Incidents(this);
        int from_bitField0_ = bitField0_;
        if (incidentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            incident_ = java.util.Collections.unmodifiableList(incident_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.incident_ = incident_;
        } else {
          result.incident_ = incidentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Incidents) {
          return mergeFrom((Incidents)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Incidents other) {
        if (other == Incidents.getDefaultInstance()) return this;
        if (incidentBuilder_ == null) {
          if (!other.incident_.isEmpty()) {
            if (incident_.isEmpty()) {
              incident_ = other.incident_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureIncidentIsMutable();
              incident_.addAll(other.incident_);
            }
            onChanged();
          }
        } else {
          if (!other.incident_.isEmpty()) {
            if (incidentBuilder_.isEmpty()) {
              incidentBuilder_.dispose();
              incidentBuilder_ = null;
              incident_ = other.incident_;
              bitField0_ = (bitField0_ & ~0x00000001);
              incidentBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getIncidentFieldBuilder() : null;
            } else {
              incidentBuilder_.addAllMessages(other.incident_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getIncidentCount(); i++) {
          if (!getIncident(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Incidents parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Incidents) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Incident> incident_ =
        java.util.Collections.emptyList();
      private void ensureIncidentIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          incident_ = new java.util.ArrayList<Incident>(incident_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Incident, Incident.Builder, IncidentOrBuilder> incidentBuilder_;

      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public java.util.List<Incident> getIncidentList() {
        if (incidentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(incident_);
        } else {
          return incidentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public int getIncidentCount() {
        if (incidentBuilder_ == null) {
          return incident_.size();
        } else {
          return incidentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Incident getIncident(int index) {
        if (incidentBuilder_ == null) {
          return incident_.get(index);
        } else {
          return incidentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Builder setIncident(
          int index, Incident value) {
        if (incidentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIncidentIsMutable();
          incident_.set(index, value);
          onChanged();
        } else {
          incidentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Builder setIncident(
          int index, Incident.Builder builderForValue) {
        if (incidentBuilder_ == null) {
          ensureIncidentIsMutable();
          incident_.set(index, builderForValue.build());
          onChanged();
        } else {
          incidentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Builder addIncident(Incident value) {
        if (incidentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIncidentIsMutable();
          incident_.add(value);
          onChanged();
        } else {
          incidentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Builder addIncident(
          int index, Incident value) {
        if (incidentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIncidentIsMutable();
          incident_.add(index, value);
          onChanged();
        } else {
          incidentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Builder addIncident(
          Incident.Builder builderForValue) {
        if (incidentBuilder_ == null) {
          ensureIncidentIsMutable();
          incident_.add(builderForValue.build());
          onChanged();
        } else {
          incidentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Builder addIncident(
          int index, Incident.Builder builderForValue) {
        if (incidentBuilder_ == null) {
          ensureIncidentIsMutable();
          incident_.add(index, builderForValue.build());
          onChanged();
        } else {
          incidentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Builder addAllIncident(
          Iterable<? extends Incident> values) {
        if (incidentBuilder_ == null) {
          ensureIncidentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, incident_);
          onChanged();
        } else {
          incidentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Builder clearIncident() {
        if (incidentBuilder_ == null) {
          incident_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          incidentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Builder removeIncident(int index) {
        if (incidentBuilder_ == null) {
          ensureIncidentIsMutable();
          incident_.remove(index);
          onChanged();
        } else {
          incidentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Incident.Builder getIncidentBuilder(
          int index) {
        return getIncidentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public IncidentOrBuilder getIncidentOrBuilder(
          int index) {
        if (incidentBuilder_ == null) {
          return incident_.get(index);  } else {
          return incidentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public java.util.List<? extends IncidentOrBuilder>
           getIncidentOrBuilderList() {
        if (incidentBuilder_ != null) {
          return incidentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(incident_);
        }
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Incident.Builder addIncidentBuilder() {
        return getIncidentFieldBuilder().addBuilder(
            Incident.getDefaultInstance());
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public Incident.Builder addIncidentBuilder(
          int index) {
        return getIncidentFieldBuilder().addBuilder(
            index, Incident.getDefaultInstance());
      }
      /**
       * <code>repeated .vigilante.Incident incident = 1;</code>
       */
      public java.util.List<Incident.Builder>
           getIncidentBuilderList() {
        return getIncidentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Incident, Incident.Builder, IncidentOrBuilder>
          getIncidentFieldBuilder() {
        if (incidentBuilder_ == null) {
          incidentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Incident, Incident.Builder, IncidentOrBuilder>(
                  incident_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          incident_ = null;
        }
        return incidentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:vigilante.Incidents)
    }

    static {
      defaultInstance = new Incidents(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:vigilante.Incidents)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vigilante_Incident_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vigilante_Incident_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vigilante_Incidents_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vigilante_Incidents_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016incident.proto\022\tvigilante\032\nteam.proto\032" +
      "\rservice.proto\"\365\001\n\010Incident\022\n\n\002id\030\001 \001(\t\022" +
      "\023\n\013description\030\002 \001(\t\022\r\n\005start\030\003 \001(\003\022\013\n\003k" +
      "ey\030\004 \001(\t\022#\n\007service\030\005 \001(\0132\022.vigilante.Se" +
      "rvice\022\035\n\004team\030\006 \001(\0132\017.vigilante.Team\022,\n\005" +
      "state\030\007 \001(\0162\035.vigilante.Incident.StateTy" +
      "pe\":\n\tStateType\022\014\n\010RESOLVED\020\000\022\r\n\tTRIGGER" +
      "ED\020\001\022\020\n\014ACKNOWLEDGED\020\002\"2\n\tIncidents\022%\n\010i" +
      "ncident\030\001 \003(\0132\023.vigilante.IncidentB\036\n\014io" +
      ".vigilanteB\016IncidentProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TeamProtos.getDescriptor(),
          ServiceProtos.getDescriptor(),
        }, assigner);
    internal_static_vigilante_Incident_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vigilante_Incident_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vigilante_Incident_descriptor,
        new String[] { "Id", "Description", "Start", "Key", "Service", "Team", "State", });
    internal_static_vigilante_Incidents_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vigilante_Incidents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vigilante_Incidents_descriptor,
        new String[] { "Incident", });
    TeamProtos.getDescriptor();
    ServiceProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
