// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package io.vigilante;

public final class ServiceProtos {
  private ServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vigilante.Service)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string key = 3;</code>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 3;</code>
     */
    String getKey();
    /**
     * <code>optional string key = 3;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional .vigilante.Team team = 4;</code>
     */
    boolean hasTeam();
    /**
     * <code>optional .vigilante.Team team = 4;</code>
     */
    TeamProtos.Team getTeam();
    /**
     * <code>optional .vigilante.Team team = 4;</code>
     */
    TeamProtos.TeamOrBuilder getTeamOrBuilder();

    /**
     * <code>optional .vigilante.Schedule schedule = 5;</code>
     */
    boolean hasSchedule();
    /**
     * <code>optional .vigilante.Schedule schedule = 5;</code>
     */
    io.vigilante.ScheduleProtos.Schedule getSchedule();
    /**
     * <code>optional .vigilante.Schedule schedule = 5;</code>
     */
    io.vigilante.ScheduleProtos.ScheduleOrBuilder getScheduleOrBuilder();
  }
  /**
   * Protobuf type {@code vigilante.Service}
   */
  public static final class Service extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vigilante.Service)
      ServiceOrBuilder {
    // Use Service.newBuilder() to construct.
    private Service(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Service(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Service defaultInstance;
    public static Service getDefaultInstance() {
      return defaultInstance;
    }

    public Service getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Service(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              key_ = bs;
              break;
            }
            case 34: {
              TeamProtos.Team.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = team_.toBuilder();
              }
              team_ = input.readMessage(TeamProtos.Team.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(team_);
                team_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              io.vigilante.ScheduleProtos.Schedule.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = schedule_.toBuilder();
              }
              schedule_ = input.readMessage(io.vigilante.ScheduleProtos.Schedule.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(schedule_);
                schedule_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServiceProtos.internal_static_vigilante_Service_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServiceProtos.internal_static_vigilante_Service_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Service.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Service> PARSER =
        new com.google.protobuf.AbstractParser<Service>() {
      public Service parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Service(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Service> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 3;
    private Object key_;
    /**
     * <code>optional string key = 3;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string key = 3;</code>
     */
    public String getKey() {
      Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEAM_FIELD_NUMBER = 4;
    private TeamProtos.Team team_;
    /**
     * <code>optional .vigilante.Team team = 4;</code>
     */
    public boolean hasTeam() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .vigilante.Team team = 4;</code>
     */
    public TeamProtos.Team getTeam() {
      return team_;
    }
    /**
     * <code>optional .vigilante.Team team = 4;</code>
     */
    public TeamProtos.TeamOrBuilder getTeamOrBuilder() {
      return team_;
    }

    public static final int SCHEDULE_FIELD_NUMBER = 5;
    private io.vigilante.ScheduleProtos.Schedule schedule_;
    /**
     * <code>optional .vigilante.Schedule schedule = 5;</code>
     */
    public boolean hasSchedule() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .vigilante.Schedule schedule = 5;</code>
     */
    public io.vigilante.ScheduleProtos.Schedule getSchedule() {
      return schedule_;
    }
    /**
     * <code>optional .vigilante.Schedule schedule = 5;</code>
     */
    public io.vigilante.ScheduleProtos.ScheduleOrBuilder getScheduleOrBuilder() {
      return schedule_;
    }

    private void initFields() {
      id_ = 0L;
      name_ = "";
      key_ = "";
      team_ = TeamProtos.Team.getDefaultInstance();
      schedule_ = io.vigilante.ScheduleProtos.Schedule.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasTeam()) {
        if (!getTeam().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasSchedule()) {
        if (!getSchedule().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, team_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, schedule_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, team_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, schedule_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Service parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Service parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Service parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Service parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Service parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Service parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Service parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Service parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Service parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Service parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Service prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vigilante.Service}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vigilante.Service)
        ServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServiceProtos.internal_static_vigilante_Service_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServiceProtos.internal_static_vigilante_Service_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Service.class, Builder.class);
      }

      // Construct using io.vigilante.ServiceProtos.Service.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTeamFieldBuilder();
          getScheduleFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (teamBuilder_ == null) {
          team_ = TeamProtos.Team.getDefaultInstance();
        } else {
          teamBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (scheduleBuilder_ == null) {
          schedule_ = io.vigilante.ScheduleProtos.Schedule.getDefaultInstance();
        } else {
          scheduleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ServiceProtos.internal_static_vigilante_Service_descriptor;
      }

      public Service getDefaultInstanceForType() {
        return Service.getDefaultInstance();
      }

      public Service build() {
        Service result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Service buildPartial() {
        Service result = new Service(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (teamBuilder_ == null) {
          result.team_ = team_;
        } else {
          result.team_ = teamBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (scheduleBuilder_ == null) {
          result.schedule_ = schedule_;
        } else {
          result.schedule_ = scheduleBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Service) {
          return mergeFrom((Service)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Service other) {
        if (other == Service.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000004;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasTeam()) {
          mergeTeam(other.getTeam());
        }
        if (other.hasSchedule()) {
          mergeSchedule(other.getSchedule());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasTeam()) {
          if (!getTeam().isInitialized()) {
            
            return false;
          }
        }
        if (hasSchedule()) {
          if (!getSchedule().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Service parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Service) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private Object key_ = "";
      /**
       * <code>optional string key = 3;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string key = 3;</code>
       */
      public String getKey() {
        Object ref = key_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string key = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 3;</code>
       */
      public Builder setKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 3;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 3;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }

      private TeamProtos.Team team_ = TeamProtos.Team.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          TeamProtos.Team, TeamProtos.Team.Builder, TeamProtos.TeamOrBuilder> teamBuilder_;
      /**
       * <code>optional .vigilante.Team team = 4;</code>
       */
      public boolean hasTeam() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .vigilante.Team team = 4;</code>
       */
      public TeamProtos.Team getTeam() {
        if (teamBuilder_ == null) {
          return team_;
        } else {
          return teamBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .vigilante.Team team = 4;</code>
       */
      public Builder setTeam(TeamProtos.Team value) {
        if (teamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          team_ = value;
          onChanged();
        } else {
          teamBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .vigilante.Team team = 4;</code>
       */
      public Builder setTeam(
          TeamProtos.Team.Builder builderForValue) {
        if (teamBuilder_ == null) {
          team_ = builderForValue.build();
          onChanged();
        } else {
          teamBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .vigilante.Team team = 4;</code>
       */
      public Builder mergeTeam(TeamProtos.Team value) {
        if (teamBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              team_ != TeamProtos.Team.getDefaultInstance()) {
            team_ =
              TeamProtos.Team.newBuilder(team_).mergeFrom(value).buildPartial();
          } else {
            team_ = value;
          }
          onChanged();
        } else {
          teamBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .vigilante.Team team = 4;</code>
       */
      public Builder clearTeam() {
        if (teamBuilder_ == null) {
          team_ = TeamProtos.Team.getDefaultInstance();
          onChanged();
        } else {
          teamBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .vigilante.Team team = 4;</code>
       */
      public TeamProtos.Team.Builder getTeamBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getTeamFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .vigilante.Team team = 4;</code>
       */
      public TeamProtos.TeamOrBuilder getTeamOrBuilder() {
        if (teamBuilder_ != null) {
          return teamBuilder_.getMessageOrBuilder();
        } else {
          return team_;
        }
      }
      /**
       * <code>optional .vigilante.Team team = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          TeamProtos.Team, TeamProtos.Team.Builder, TeamProtos.TeamOrBuilder>
          getTeamFieldBuilder() {
        if (teamBuilder_ == null) {
          teamBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              TeamProtos.Team, TeamProtos.Team.Builder, TeamProtos.TeamOrBuilder>(
                  getTeam(),
                  getParentForChildren(),
                  isClean());
          team_ = null;
        }
        return teamBuilder_;
      }

      private io.vigilante.ScheduleProtos.Schedule schedule_ = io.vigilante.ScheduleProtos.Schedule.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          io.vigilante.ScheduleProtos.Schedule, io.vigilante.ScheduleProtos.Schedule.Builder, io.vigilante.ScheduleProtos.ScheduleOrBuilder> scheduleBuilder_;
      /**
       * <code>optional .vigilante.Schedule schedule = 5;</code>
       */
      public boolean hasSchedule() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .vigilante.Schedule schedule = 5;</code>
       */
      public io.vigilante.ScheduleProtos.Schedule getSchedule() {
        if (scheduleBuilder_ == null) {
          return schedule_;
        } else {
          return scheduleBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .vigilante.Schedule schedule = 5;</code>
       */
      public Builder setSchedule(io.vigilante.ScheduleProtos.Schedule value) {
        if (scheduleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          schedule_ = value;
          onChanged();
        } else {
          scheduleBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .vigilante.Schedule schedule = 5;</code>
       */
      public Builder setSchedule(
          io.vigilante.ScheduleProtos.Schedule.Builder builderForValue) {
        if (scheduleBuilder_ == null) {
          schedule_ = builderForValue.build();
          onChanged();
        } else {
          scheduleBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .vigilante.Schedule schedule = 5;</code>
       */
      public Builder mergeSchedule(io.vigilante.ScheduleProtos.Schedule value) {
        if (scheduleBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              schedule_ != io.vigilante.ScheduleProtos.Schedule.getDefaultInstance()) {
            schedule_ =
              io.vigilante.ScheduleProtos.Schedule.newBuilder(schedule_).mergeFrom(value).buildPartial();
          } else {
            schedule_ = value;
          }
          onChanged();
        } else {
          scheduleBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .vigilante.Schedule schedule = 5;</code>
       */
      public Builder clearSchedule() {
        if (scheduleBuilder_ == null) {
          schedule_ = io.vigilante.ScheduleProtos.Schedule.getDefaultInstance();
          onChanged();
        } else {
          scheduleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .vigilante.Schedule schedule = 5;</code>
       */
      public io.vigilante.ScheduleProtos.Schedule.Builder getScheduleBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getScheduleFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .vigilante.Schedule schedule = 5;</code>
       */
      public io.vigilante.ScheduleProtos.ScheduleOrBuilder getScheduleOrBuilder() {
        if (scheduleBuilder_ != null) {
          return scheduleBuilder_.getMessageOrBuilder();
        } else {
          return schedule_;
        }
      }
      /**
       * <code>optional .vigilante.Schedule schedule = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          io.vigilante.ScheduleProtos.Schedule, io.vigilante.ScheduleProtos.Schedule.Builder, io.vigilante.ScheduleProtos.ScheduleOrBuilder> 
          getScheduleFieldBuilder() {
        if (scheduleBuilder_ == null) {
          scheduleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.vigilante.ScheduleProtos.Schedule, io.vigilante.ScheduleProtos.Schedule.Builder, io.vigilante.ScheduleProtos.ScheduleOrBuilder>(
                  getSchedule(),
                  getParentForChildren(),
                  isClean());
          schedule_ = null;
        }
        return scheduleBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:vigilante.Service)
    }

    static {
      defaultInstance = new Service(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:vigilante.Service)
  }

  public interface ServicesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vigilante.Services)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .vigilante.Service services = 1;</code>
     */
    java.util.List<Service>
        getServicesList();
    /**
     * <code>repeated .vigilante.Service services = 1;</code>
     */
    Service getServices(int index);
    /**
     * <code>repeated .vigilante.Service services = 1;</code>
     */
    int getServicesCount();
    /**
     * <code>repeated .vigilante.Service services = 1;</code>
     */
    java.util.List<? extends ServiceOrBuilder>
        getServicesOrBuilderList();
    /**
     * <code>repeated .vigilante.Service services = 1;</code>
     */
    ServiceOrBuilder getServicesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code vigilante.Services}
   */
  public static final class Services extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vigilante.Services)
      ServicesOrBuilder {
    // Use Services.newBuilder() to construct.
    private Services(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Services(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Services defaultInstance;
    public static Services getDefaultInstance() {
      return defaultInstance;
    }

    public Services getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Services(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                services_ = new java.util.ArrayList<Service>();
                mutable_bitField0_ |= 0x00000001;
              }
              services_.add(input.readMessage(Service.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          services_ = java.util.Collections.unmodifiableList(services_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServiceProtos.internal_static_vigilante_Services_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServiceProtos.internal_static_vigilante_Services_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Services.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Services> PARSER =
        new com.google.protobuf.AbstractParser<Services>() {
      public Services parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Services(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Services> getParserForType() {
      return PARSER;
    }

    public static final int SERVICES_FIELD_NUMBER = 1;
    private java.util.List<Service> services_;
    /**
     * <code>repeated .vigilante.Service services = 1;</code>
     */
    public java.util.List<Service> getServicesList() {
      return services_;
    }
    /**
     * <code>repeated .vigilante.Service services = 1;</code>
     */
    public java.util.List<? extends ServiceOrBuilder>
        getServicesOrBuilderList() {
      return services_;
    }
    /**
     * <code>repeated .vigilante.Service services = 1;</code>
     */
    public int getServicesCount() {
      return services_.size();
    }
    /**
     * <code>repeated .vigilante.Service services = 1;</code>
     */
    public Service getServices(int index) {
      return services_.get(index);
    }
    /**
     * <code>repeated .vigilante.Service services = 1;</code>
     */
    public ServiceOrBuilder getServicesOrBuilder(
        int index) {
      return services_.get(index);
    }

    private void initFields() {
      services_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getServicesCount(); i++) {
        if (!getServices(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < services_.size(); i++) {
        output.writeMessage(1, services_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < services_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, services_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Services parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Services parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Services parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Services parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Services parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Services parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Services parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Services parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Services parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Services parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Services prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vigilante.Services}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vigilante.Services)
        ServicesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServiceProtos.internal_static_vigilante_Services_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServiceProtos.internal_static_vigilante_Services_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Services.class, Builder.class);
      }

      // Construct using io.vigilante.ServiceProtos.Services.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getServicesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (servicesBuilder_ == null) {
          services_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          servicesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ServiceProtos.internal_static_vigilante_Services_descriptor;
      }

      public Services getDefaultInstanceForType() {
        return Services.getDefaultInstance();
      }

      public Services build() {
        Services result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Services buildPartial() {
        Services result = new Services(this);
        int from_bitField0_ = bitField0_;
        if (servicesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            services_ = java.util.Collections.unmodifiableList(services_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.services_ = services_;
        } else {
          result.services_ = servicesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Services) {
          return mergeFrom((Services)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Services other) {
        if (other == Services.getDefaultInstance()) return this;
        if (servicesBuilder_ == null) {
          if (!other.services_.isEmpty()) {
            if (services_.isEmpty()) {
              services_ = other.services_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureServicesIsMutable();
              services_.addAll(other.services_);
            }
            onChanged();
          }
        } else {
          if (!other.services_.isEmpty()) {
            if (servicesBuilder_.isEmpty()) {
              servicesBuilder_.dispose();
              servicesBuilder_ = null;
              services_ = other.services_;
              bitField0_ = (bitField0_ & ~0x00000001);
              servicesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getServicesFieldBuilder() : null;
            } else {
              servicesBuilder_.addAllMessages(other.services_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getServicesCount(); i++) {
          if (!getServices(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Services parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Services) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Service> services_ =
        java.util.Collections.emptyList();
      private void ensureServicesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          services_ = new java.util.ArrayList<Service>(services_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Service, Service.Builder, ServiceOrBuilder> servicesBuilder_;

      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public java.util.List<Service> getServicesList() {
        if (servicesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(services_);
        } else {
          return servicesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public int getServicesCount() {
        if (servicesBuilder_ == null) {
          return services_.size();
        } else {
          return servicesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Service getServices(int index) {
        if (servicesBuilder_ == null) {
          return services_.get(index);
        } else {
          return servicesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Builder setServices(
          int index, Service value) {
        if (servicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServicesIsMutable();
          services_.set(index, value);
          onChanged();
        } else {
          servicesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Builder setServices(
          int index, Service.Builder builderForValue) {
        if (servicesBuilder_ == null) {
          ensureServicesIsMutable();
          services_.set(index, builderForValue.build());
          onChanged();
        } else {
          servicesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Builder addServices(Service value) {
        if (servicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServicesIsMutable();
          services_.add(value);
          onChanged();
        } else {
          servicesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Builder addServices(
          int index, Service value) {
        if (servicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServicesIsMutable();
          services_.add(index, value);
          onChanged();
        } else {
          servicesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Builder addServices(
          Service.Builder builderForValue) {
        if (servicesBuilder_ == null) {
          ensureServicesIsMutable();
          services_.add(builderForValue.build());
          onChanged();
        } else {
          servicesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Builder addServices(
          int index, Service.Builder builderForValue) {
        if (servicesBuilder_ == null) {
          ensureServicesIsMutable();
          services_.add(index, builderForValue.build());
          onChanged();
        } else {
          servicesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Builder addAllServices(
          Iterable<? extends Service> values) {
        if (servicesBuilder_ == null) {
          ensureServicesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, services_);
          onChanged();
        } else {
          servicesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Builder clearServices() {
        if (servicesBuilder_ == null) {
          services_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          servicesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Builder removeServices(int index) {
        if (servicesBuilder_ == null) {
          ensureServicesIsMutable();
          services_.remove(index);
          onChanged();
        } else {
          servicesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Service.Builder getServicesBuilder(
          int index) {
        return getServicesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public ServiceOrBuilder getServicesOrBuilder(
          int index) {
        if (servicesBuilder_ == null) {
          return services_.get(index);  } else {
          return servicesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public java.util.List<? extends ServiceOrBuilder>
           getServicesOrBuilderList() {
        if (servicesBuilder_ != null) {
          return servicesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(services_);
        }
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Service.Builder addServicesBuilder() {
        return getServicesFieldBuilder().addBuilder(
            Service.getDefaultInstance());
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public Service.Builder addServicesBuilder(
          int index) {
        return getServicesFieldBuilder().addBuilder(
            index, Service.getDefaultInstance());
      }
      /**
       * <code>repeated .vigilante.Service services = 1;</code>
       */
      public java.util.List<Service.Builder>
           getServicesBuilderList() {
        return getServicesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Service, Service.Builder, ServiceOrBuilder>
          getServicesFieldBuilder() {
        if (servicesBuilder_ == null) {
          servicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Service, Service.Builder, ServiceOrBuilder>(
                  services_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          services_ = null;
        }
        return servicesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:vigilante.Services)
    }

    static {
      defaultInstance = new Services(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:vigilante.Services)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vigilante_Service_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vigilante_Service_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vigilante_Services_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vigilante_Services_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rservice.proto\022\tvigilante\032\nteam.proto\032\016" +
      "schedule.proto\"v\n\007Service\022\n\n\002id\030\001 \001(\003\022\014\n" +
      "\004name\030\002 \001(\t\022\013\n\003key\030\003 \001(\t\022\035\n\004team\030\004 \001(\0132\017" +
      ".vigilante.Team\022%\n\010schedule\030\005 \001(\0132\023.vigi" +
      "lante.Schedule\"0\n\010Services\022$\n\010services\030\001" +
      " \003(\0132\022.vigilante.ServiceB\035\n\014io.vigilante" +
      "B\rServiceProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TeamProtos.getDescriptor(),
          io.vigilante.ScheduleProtos.getDescriptor(),
        }, assigner);
    internal_static_vigilante_Service_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vigilante_Service_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vigilante_Service_descriptor,
        new String[] { "Id", "Name", "Key", "Team", "Schedule", });
    internal_static_vigilante_Services_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vigilante_Services_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vigilante_Services_descriptor,
        new String[] { "Services", });
    TeamProtos.getDescriptor();
    io.vigilante.ScheduleProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
