// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: useroncall.proto

package io.vigilante;

public final class UserOnCallProtos {
  private UserOnCallProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOnCallOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vigilante.UserOnCall)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 3;</code>
     */
    String getEmail();
    /**
     * <code>required string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>required string time_zone = 4;</code>
     */
    boolean hasTimeZone();
    /**
     * <code>required string time_zone = 4;</code>
     */
    String getTimeZone();
    /**
     * <code>required string time_zone = 4;</code>
     */
    com.google.protobuf.ByteString
        getTimeZoneBytes();

    /**
     * <code>required int32 level = 5;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 5;</code>
     */
    int getLevel();

    /**
     * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
     */
    java.util.List<UserProtos.User.NotificationRule>
        getNotificationsList();
    /**
     * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
     */
    UserProtos.User.NotificationRule getNotifications(int index);
    /**
     * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
     */
    int getNotificationsCount();
    /**
     * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
     */
    java.util.List<? extends UserProtos.User.NotificationRuleOrBuilder>
        getNotificationsOrBuilderList();
    /**
     * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
     */
    UserProtos.User.NotificationRuleOrBuilder getNotificationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code vigilante.UserOnCall}
   */
  public static final class UserOnCall extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vigilante.UserOnCall)
      UserOnCallOrBuilder {
    // Use UserOnCall.newBuilder() to construct.
    private UserOnCall(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserOnCall(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserOnCall defaultInstance;
    public static UserOnCall getDefaultInstance() {
      return defaultInstance;
    }

    public UserOnCall getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserOnCall(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              email_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              timeZone_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              level_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                notifications_ = new java.util.ArrayList<UserProtos.User.NotificationRule>();
                mutable_bitField0_ |= 0x00000020;
              }
              notifications_.add(input.readMessage(UserProtos.User.NotificationRule.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          notifications_ = java.util.Collections.unmodifiableList(notifications_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserOnCallProtos.internal_static_vigilante_UserOnCall_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserOnCallProtos.internal_static_vigilante_UserOnCall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserOnCall.class, Builder.class);
    }

    public static com.google.protobuf.Parser<UserOnCall> PARSER =
        new com.google.protobuf.AbstractParser<UserOnCall>() {
      public UserOnCall parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserOnCall(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<UserOnCall> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private Object email_;
    /**
     * <code>required string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string email = 3;</code>
     */
    public String getEmail() {
      Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_ZONE_FIELD_NUMBER = 4;
    private Object timeZone_;
    /**
     * <code>required string time_zone = 4;</code>
     */
    public boolean hasTimeZone() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string time_zone = 4;</code>
     */
    public String getTimeZone() {
      Object ref = timeZone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeZone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time_zone = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTimeZoneBytes() {
      Object ref = timeZone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        timeZone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 5;
    private int level_;
    /**
     * <code>required int32 level = 5;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 level = 5;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int NOTIFICATIONS_FIELD_NUMBER = 6;
    private java.util.List<UserProtos.User.NotificationRule> notifications_;
    /**
     * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
     */
    public java.util.List<UserProtos.User.NotificationRule> getNotificationsList() {
      return notifications_;
    }
    /**
     * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
     */
    public java.util.List<? extends UserProtos.User.NotificationRuleOrBuilder>
        getNotificationsOrBuilderList() {
      return notifications_;
    }
    /**
     * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
     */
    public int getNotificationsCount() {
      return notifications_.size();
    }
    /**
     * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
     */
    public UserProtos.User.NotificationRule getNotifications(int index) {
      return notifications_.get(index);
    }
    /**
     * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
     */
    public UserProtos.User.NotificationRuleOrBuilder getNotificationsOrBuilder(
        int index) {
      return notifications_.get(index);
    }

    private void initFields() {
      id_ = 0L;
      name_ = "";
      email_ = "";
      timeZone_ = "";
      level_ = 0;
      notifications_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeZone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getNotificationsCount(); i++) {
        if (!getNotifications(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTimeZoneBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, level_);
      }
      for (int i = 0; i < notifications_.size(); i++) {
        output.writeMessage(6, notifications_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTimeZoneBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, level_);
      }
      for (int i = 0; i < notifications_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, notifications_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static UserOnCall parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserOnCall parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserOnCall parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserOnCall parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserOnCall parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UserOnCall parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static UserOnCall parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static UserOnCall parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static UserOnCall parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UserOnCall parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UserOnCall prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vigilante.UserOnCall}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vigilante.UserOnCall)
        UserOnCallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserOnCallProtos.internal_static_vigilante_UserOnCall_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserOnCallProtos.internal_static_vigilante_UserOnCall_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserOnCall.class, Builder.class);
      }

      // Construct using io.vigilante.UserOnCallProtos.UserOnCall.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNotificationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        timeZone_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (notificationsBuilder_ == null) {
          notifications_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          notificationsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserOnCallProtos.internal_static_vigilante_UserOnCall_descriptor;
      }

      public UserOnCall getDefaultInstanceForType() {
        return UserOnCall.getDefaultInstance();
      }

      public UserOnCall build() {
        UserOnCall result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UserOnCall buildPartial() {
        UserOnCall result = new UserOnCall(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timeZone_ = timeZone_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.level_ = level_;
        if (notificationsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            notifications_ = java.util.Collections.unmodifiableList(notifications_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.notifications_ = notifications_;
        } else {
          result.notifications_ = notificationsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserOnCall) {
          return mergeFrom((UserOnCall)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserOnCall other) {
        if (other == UserOnCall.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasTimeZone()) {
          bitField0_ |= 0x00000008;
          timeZone_ = other.timeZone_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (notificationsBuilder_ == null) {
          if (!other.notifications_.isEmpty()) {
            if (notifications_.isEmpty()) {
              notifications_ = other.notifications_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureNotificationsIsMutable();
              notifications_.addAll(other.notifications_);
            }
            onChanged();
          }
        } else {
          if (!other.notifications_.isEmpty()) {
            if (notificationsBuilder_.isEmpty()) {
              notificationsBuilder_.dispose();
              notificationsBuilder_ = null;
              notifications_ = other.notifications_;
              bitField0_ = (bitField0_ & ~0x00000020);
              notificationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNotificationsFieldBuilder() : null;
            } else {
              notificationsBuilder_.addAllMessages(other.notifications_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        if (!hasTimeZone()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        for (int i = 0; i < getNotificationsCount(); i++) {
          if (!getNotifications(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserOnCall parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserOnCall) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private Object email_ = "";
      /**
       * <code>required string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string email = 3;</code>
       */
      public String getEmail() {
        Object ref = email_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder setEmail(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      private Object timeZone_ = "";
      /**
       * <code>required string time_zone = 4;</code>
       */
      public boolean hasTimeZone() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string time_zone = 4;</code>
       */
      public String getTimeZone() {
        Object ref = timeZone_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timeZone_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string time_zone = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTimeZoneBytes() {
        Object ref = timeZone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          timeZone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time_zone = 4;</code>
       */
      public Builder setTimeZone(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        timeZone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time_zone = 4;</code>
       */
      public Builder clearTimeZone() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timeZone_ = getDefaultInstance().getTimeZone();
        onChanged();
        return this;
      }
      /**
       * <code>required string time_zone = 4;</code>
       */
      public Builder setTimeZoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        timeZone_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>required int32 level = 5;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 level = 5;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 5;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000010;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 5;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<UserProtos.User.NotificationRule> notifications_ =
        java.util.Collections.emptyList();
      private void ensureNotificationsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          notifications_ = new java.util.ArrayList<UserProtos.User.NotificationRule>(notifications_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          UserProtos.User.NotificationRule, UserProtos.User.NotificationRule.Builder, UserProtos.User.NotificationRuleOrBuilder> notificationsBuilder_;

      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public java.util.List<UserProtos.User.NotificationRule> getNotificationsList() {
        if (notificationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(notifications_);
        } else {
          return notificationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public int getNotificationsCount() {
        if (notificationsBuilder_ == null) {
          return notifications_.size();
        } else {
          return notificationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public UserProtos.User.NotificationRule getNotifications(int index) {
        if (notificationsBuilder_ == null) {
          return notifications_.get(index);
        } else {
          return notificationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public Builder setNotifications(
          int index, UserProtos.User.NotificationRule value) {
        if (notificationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotificationsIsMutable();
          notifications_.set(index, value);
          onChanged();
        } else {
          notificationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public Builder setNotifications(
          int index, UserProtos.User.NotificationRule.Builder builderForValue) {
        if (notificationsBuilder_ == null) {
          ensureNotificationsIsMutable();
          notifications_.set(index, builderForValue.build());
          onChanged();
        } else {
          notificationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public Builder addNotifications(UserProtos.User.NotificationRule value) {
        if (notificationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotificationsIsMutable();
          notifications_.add(value);
          onChanged();
        } else {
          notificationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public Builder addNotifications(
          int index, UserProtos.User.NotificationRule value) {
        if (notificationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotificationsIsMutable();
          notifications_.add(index, value);
          onChanged();
        } else {
          notificationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public Builder addNotifications(
          UserProtos.User.NotificationRule.Builder builderForValue) {
        if (notificationsBuilder_ == null) {
          ensureNotificationsIsMutable();
          notifications_.add(builderForValue.build());
          onChanged();
        } else {
          notificationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public Builder addNotifications(
          int index, UserProtos.User.NotificationRule.Builder builderForValue) {
        if (notificationsBuilder_ == null) {
          ensureNotificationsIsMutable();
          notifications_.add(index, builderForValue.build());
          onChanged();
        } else {
          notificationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public Builder addAllNotifications(
          Iterable<? extends UserProtos.User.NotificationRule> values) {
        if (notificationsBuilder_ == null) {
          ensureNotificationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, notifications_);
          onChanged();
        } else {
          notificationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public Builder clearNotifications() {
        if (notificationsBuilder_ == null) {
          notifications_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          notificationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public Builder removeNotifications(int index) {
        if (notificationsBuilder_ == null) {
          ensureNotificationsIsMutable();
          notifications_.remove(index);
          onChanged();
        } else {
          notificationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public UserProtos.User.NotificationRule.Builder getNotificationsBuilder(
          int index) {
        return getNotificationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public UserProtos.User.NotificationRuleOrBuilder getNotificationsOrBuilder(
          int index) {
        if (notificationsBuilder_ == null) {
          return notifications_.get(index);  } else {
          return notificationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public java.util.List<? extends UserProtos.User.NotificationRuleOrBuilder>
           getNotificationsOrBuilderList() {
        if (notificationsBuilder_ != null) {
          return notificationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(notifications_);
        }
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public UserProtos.User.NotificationRule.Builder addNotificationsBuilder() {
        return getNotificationsFieldBuilder().addBuilder(
            UserProtos.User.NotificationRule.getDefaultInstance());
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public UserProtos.User.NotificationRule.Builder addNotificationsBuilder(
          int index) {
        return getNotificationsFieldBuilder().addBuilder(
            index, UserProtos.User.NotificationRule.getDefaultInstance());
      }
      /**
       * <code>repeated .vigilante.User.NotificationRule notifications = 6;</code>
       */
      public java.util.List<UserProtos.User.NotificationRule.Builder>
           getNotificationsBuilderList() {
        return getNotificationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          UserProtos.User.NotificationRule, UserProtos.User.NotificationRule.Builder, UserProtos.User.NotificationRuleOrBuilder>
          getNotificationsFieldBuilder() {
        if (notificationsBuilder_ == null) {
          notificationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              UserProtos.User.NotificationRule, UserProtos.User.NotificationRule.Builder, UserProtos.User.NotificationRuleOrBuilder>(
                  notifications_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          notifications_ = null;
        }
        return notificationsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:vigilante.UserOnCall)
    }

    static {
      defaultInstance = new UserOnCall(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:vigilante.UserOnCall)
  }

  public interface UsersOnCallOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vigilante.UsersOnCall)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
     */
    java.util.List<UserOnCall>
        getUserOnCallList();
    /**
     * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
     */
    UserOnCall getUserOnCall(int index);
    /**
     * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
     */
    int getUserOnCallCount();
    /**
     * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
     */
    java.util.List<? extends UserOnCallOrBuilder>
        getUserOnCallOrBuilderList();
    /**
     * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
     */
    UserOnCallOrBuilder getUserOnCallOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code vigilante.UsersOnCall}
   */
  public static final class UsersOnCall extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vigilante.UsersOnCall)
      UsersOnCallOrBuilder {
    // Use UsersOnCall.newBuilder() to construct.
    private UsersOnCall(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UsersOnCall(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UsersOnCall defaultInstance;
    public static UsersOnCall getDefaultInstance() {
      return defaultInstance;
    }

    public UsersOnCall getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UsersOnCall(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                userOnCall_ = new java.util.ArrayList<UserOnCall>();
                mutable_bitField0_ |= 0x00000001;
              }
              userOnCall_.add(input.readMessage(UserOnCall.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          userOnCall_ = java.util.Collections.unmodifiableList(userOnCall_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserOnCallProtos.internal_static_vigilante_UsersOnCall_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserOnCallProtos.internal_static_vigilante_UsersOnCall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UsersOnCall.class, Builder.class);
    }

    public static com.google.protobuf.Parser<UsersOnCall> PARSER =
        new com.google.protobuf.AbstractParser<UsersOnCall>() {
      public UsersOnCall parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UsersOnCall(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<UsersOnCall> getParserForType() {
      return PARSER;
    }

    public static final int USERONCALL_FIELD_NUMBER = 1;
    private java.util.List<UserOnCall> userOnCall_;
    /**
     * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
     */
    public java.util.List<UserOnCall> getUserOnCallList() {
      return userOnCall_;
    }
    /**
     * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
     */
    public java.util.List<? extends UserOnCallOrBuilder>
        getUserOnCallOrBuilderList() {
      return userOnCall_;
    }
    /**
     * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
     */
    public int getUserOnCallCount() {
      return userOnCall_.size();
    }
    /**
     * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
     */
    public UserOnCall getUserOnCall(int index) {
      return userOnCall_.get(index);
    }
    /**
     * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
     */
    public UserOnCallOrBuilder getUserOnCallOrBuilder(
        int index) {
      return userOnCall_.get(index);
    }

    private void initFields() {
      userOnCall_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getUserOnCallCount(); i++) {
        if (!getUserOnCall(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < userOnCall_.size(); i++) {
        output.writeMessage(1, userOnCall_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < userOnCall_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userOnCall_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static UsersOnCall parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UsersOnCall parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UsersOnCall parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UsersOnCall parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UsersOnCall parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UsersOnCall parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static UsersOnCall parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static UsersOnCall parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static UsersOnCall parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UsersOnCall parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UsersOnCall prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vigilante.UsersOnCall}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vigilante.UsersOnCall)
        UsersOnCallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserOnCallProtos.internal_static_vigilante_UsersOnCall_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserOnCallProtos.internal_static_vigilante_UsersOnCall_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UsersOnCall.class, Builder.class);
      }

      // Construct using io.vigilante.UserOnCallProtos.UsersOnCall.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserOnCallFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userOnCallBuilder_ == null) {
          userOnCall_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userOnCallBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserOnCallProtos.internal_static_vigilante_UsersOnCall_descriptor;
      }

      public UsersOnCall getDefaultInstanceForType() {
        return UsersOnCall.getDefaultInstance();
      }

      public UsersOnCall build() {
        UsersOnCall result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UsersOnCall buildPartial() {
        UsersOnCall result = new UsersOnCall(this);
        int from_bitField0_ = bitField0_;
        if (userOnCallBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            userOnCall_ = java.util.Collections.unmodifiableList(userOnCall_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.userOnCall_ = userOnCall_;
        } else {
          result.userOnCall_ = userOnCallBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UsersOnCall) {
          return mergeFrom((UsersOnCall)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UsersOnCall other) {
        if (other == UsersOnCall.getDefaultInstance()) return this;
        if (userOnCallBuilder_ == null) {
          if (!other.userOnCall_.isEmpty()) {
            if (userOnCall_.isEmpty()) {
              userOnCall_ = other.userOnCall_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserOnCallIsMutable();
              userOnCall_.addAll(other.userOnCall_);
            }
            onChanged();
          }
        } else {
          if (!other.userOnCall_.isEmpty()) {
            if (userOnCallBuilder_.isEmpty()) {
              userOnCallBuilder_.dispose();
              userOnCallBuilder_ = null;
              userOnCall_ = other.userOnCall_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userOnCallBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUserOnCallFieldBuilder() : null;
            } else {
              userOnCallBuilder_.addAllMessages(other.userOnCall_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getUserOnCallCount(); i++) {
          if (!getUserOnCall(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UsersOnCall parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UsersOnCall) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<UserOnCall> userOnCall_ =
        java.util.Collections.emptyList();
      private void ensureUserOnCallIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          userOnCall_ = new java.util.ArrayList<UserOnCall>(userOnCall_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          UserOnCall, UserOnCall.Builder, UserOnCallOrBuilder> userOnCallBuilder_;

      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public java.util.List<UserOnCall> getUserOnCallList() {
        if (userOnCallBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userOnCall_);
        } else {
          return userOnCallBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public int getUserOnCallCount() {
        if (userOnCallBuilder_ == null) {
          return userOnCall_.size();
        } else {
          return userOnCallBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public UserOnCall getUserOnCall(int index) {
        if (userOnCallBuilder_ == null) {
          return userOnCall_.get(index);
        } else {
          return userOnCallBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public Builder setUserOnCall(
          int index, UserOnCall value) {
        if (userOnCallBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserOnCallIsMutable();
          userOnCall_.set(index, value);
          onChanged();
        } else {
          userOnCallBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public Builder setUserOnCall(
          int index, UserOnCall.Builder builderForValue) {
        if (userOnCallBuilder_ == null) {
          ensureUserOnCallIsMutable();
          userOnCall_.set(index, builderForValue.build());
          onChanged();
        } else {
          userOnCallBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public Builder addUserOnCall(UserOnCall value) {
        if (userOnCallBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserOnCallIsMutable();
          userOnCall_.add(value);
          onChanged();
        } else {
          userOnCallBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public Builder addUserOnCall(
          int index, UserOnCall value) {
        if (userOnCallBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserOnCallIsMutable();
          userOnCall_.add(index, value);
          onChanged();
        } else {
          userOnCallBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public Builder addUserOnCall(
          UserOnCall.Builder builderForValue) {
        if (userOnCallBuilder_ == null) {
          ensureUserOnCallIsMutable();
          userOnCall_.add(builderForValue.build());
          onChanged();
        } else {
          userOnCallBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public Builder addUserOnCall(
          int index, UserOnCall.Builder builderForValue) {
        if (userOnCallBuilder_ == null) {
          ensureUserOnCallIsMutable();
          userOnCall_.add(index, builderForValue.build());
          onChanged();
        } else {
          userOnCallBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public Builder addAllUserOnCall(
          Iterable<? extends UserOnCall> values) {
        if (userOnCallBuilder_ == null) {
          ensureUserOnCallIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userOnCall_);
          onChanged();
        } else {
          userOnCallBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public Builder clearUserOnCall() {
        if (userOnCallBuilder_ == null) {
          userOnCall_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userOnCallBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public Builder removeUserOnCall(int index) {
        if (userOnCallBuilder_ == null) {
          ensureUserOnCallIsMutable();
          userOnCall_.remove(index);
          onChanged();
        } else {
          userOnCallBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public UserOnCall.Builder getUserOnCallBuilder(
          int index) {
        return getUserOnCallFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public UserOnCallOrBuilder getUserOnCallOrBuilder(
          int index) {
        if (userOnCallBuilder_ == null) {
          return userOnCall_.get(index);  } else {
          return userOnCallBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public java.util.List<? extends UserOnCallOrBuilder>
           getUserOnCallOrBuilderList() {
        if (userOnCallBuilder_ != null) {
          return userOnCallBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userOnCall_);
        }
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public UserOnCall.Builder addUserOnCallBuilder() {
        return getUserOnCallFieldBuilder().addBuilder(
            UserOnCall.getDefaultInstance());
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public UserOnCall.Builder addUserOnCallBuilder(
          int index) {
        return getUserOnCallFieldBuilder().addBuilder(
            index, UserOnCall.getDefaultInstance());
      }
      /**
       * <code>repeated .vigilante.UserOnCall UserOnCall = 1;</code>
       */
      public java.util.List<UserOnCall.Builder>
           getUserOnCallBuilderList() {
        return getUserOnCallFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          UserOnCall, UserOnCall.Builder, UserOnCallOrBuilder>
          getUserOnCallFieldBuilder() {
        if (userOnCallBuilder_ == null) {
          userOnCallBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              UserOnCall, UserOnCall.Builder, UserOnCallOrBuilder>(
                  userOnCall_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          userOnCall_ = null;
        }
        return userOnCallBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:vigilante.UsersOnCall)
    }

    static {
      defaultInstance = new UsersOnCall(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:vigilante.UsersOnCall)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vigilante_UserOnCall_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vigilante_UserOnCall_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vigilante_UsersOnCall_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vigilante_UsersOnCall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020useroncall.proto\022\tvigilante\032\nuser.prot" +
      "o\"\220\001\n\nUserOnCall\022\n\n\002id\030\001 \002(\003\022\014\n\004name\030\002 \002" +
      "(\t\022\r\n\005email\030\003 \002(\t\022\021\n\ttime_zone\030\004 \002(\t\022\r\n\005" +
      "level\030\005 \002(\005\0227\n\rnotifications\030\006 \003(\0132 .vig" +
      "ilante.User.NotificationRule\"8\n\013UsersOnC" +
      "all\022)\n\nUserOnCall\030\001 \003(\0132\025.vigilante.User" +
      "OnCallB \n\014io.vigilanteB\020UserOnCallProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          UserProtos.getDescriptor(),
        }, assigner);
    internal_static_vigilante_UserOnCall_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vigilante_UserOnCall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vigilante_UserOnCall_descriptor,
        new String[] { "Id", "Name", "Email", "TimeZone", "Level", "Notifications", });
    internal_static_vigilante_UsersOnCall_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vigilante_UsersOnCall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vigilante_UsersOnCall_descriptor,
        new String[] { "UserOnCall", });
    UserProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
